print("Hey, wassup.")
print("What's your name?")
name = input(" ")
print("Hello", name + ", how are you doing today?")
r = input("")
bad = "The dog."
print(bad)
print("How are you today?")
print("Something is odd.")
print("d")
print(f"{name}, why did you leave?")
print("Oh dear, now we have three running code-spaces...")
print("Can you see the code that I'm printing right now?")
print("I'm magical")
print("This is very very weird...")

print(" EEEEEEEEEE  EE          EEEEEEEEEE      ")
print(" EE          EE              EE     ")
print(" EE          EE              EE    ")
print(" EE          EE              EE    ")
print(" EEEEEEEEEE  EE              EE     ")
print(" EE          EE              EE    ")
print(" EE          EE              EE     ")
print(" EE          EE              EE       EEE  EEE EEE  ")
print(" EEEEEEEEEE  EEEEEEEEEE  EEEEEEEEEE   EEE  EEE EEE      ")
